name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  showEvents:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |-
          cat << 'EOF'
          ${{  toJSON(github) }}
          EOF
